### ISSUE TITLE
Footprints

### ISSUE THREAD

**Issue by Sommema4** [mlab-modules/STEPBUBODC01#1]
Pridelit footprinty F1 a D1.

**Comment by roman-dvorak** [comment]
## F1
Jakou pojistku by sis tam představoval? Nějakou PTC? 

Takhle velkou pojistku nemáme, když se podívám, co lze koupit, tak obvykle je to v pouzdru 2920, pro tento proud. 

Jaký význam tam přesně ta pojistka má mít? Protože ji tam úplně nechápu. Obvod TPS631000 má sám o sobě overcurrent protection a short-circuit protection. 

## D1
Didodu M4 jinde používáme tuto: https://www.tme.eu/Document/0550e9bf27627c5cdfb653945cb570ca/m1-m7.pdf
