### ISSUE TITLE
Nastavování MOD a EN pinů

### ISSUE THREAD

**Issue by roman-dvorak** [mlab-modules/STEPBUBODC01#4]
Vypínání měniče a změnu jeho módu bych navrhoval vyřešit pomocí pullupu. Ne jumperu s přendaváním mezi dvěma piny. Druhý stav by se zapl právě vložením jumperu.

 * Pin nemá být ve floating stavu. V případě, že bude potřeba z nějakého důvodu vypnout/zapnout měnič za jeho provozu, tak při přepínání se tento pin dostane do floating stavu. 
 * Nasazení jumperu je další krok při výrobě. Při jeho absenci je pak pin v nedefinovaném stavu. 
 * Pokud je pin ovládán z nějakého MCU, tak MCU může nějakou dobu být ve stavu, kdy je pin taktéž ve floating stavu. 

![obrazek](https://github.com/mlab-modules/STEPBUBODC01/assets/5196729/507ad50f-2db5-4d1e-9da4-d8c6fc147a0c)

**Comment by Sommema4** [comment]
Souhlasím. Předělám.

**Comment by roman-dvorak** [comment]
Tady #[512914b](https://github.com/mlab-modules/STEPBUBODC01/commit/512914b43249f866be71e1ca22c3254c5a4c50b3) jsem to již implementoval
