### ISSUE TITLE
Chybí pouzdro k TPS obvodu

### ISSUE THREAD

**Issue by roman-dvorak** [mlab-modules/STEPBUBODC01#5]
Pouzdro k TPS obvodu není uložený v žádné sdílené knihovně. Tu je ideální uložit do MLAB knihovny: https://github.com/MLAB-project/kicad-mlab

![obrazek](https://github.com/mlab-modules/STEPBUBODC01/assets/5196729/acf757c7-3267-4c76-abde-f9a0e434f26d)

**Comment by ChroustJan** [comment]
Opravil jsem pouzdro a dal do knihovny MLAB.
